export interface Tool {
  id: string
  name: string
  slug: string
  description: string
  category: 'teks' | 'gambar' | 'audio' | 'video' | 'dev' | 'jaringan' | 'generator' | 'bahasa'
  icon: string
}

export const tools: Tool[] = [
  // Text Tools
  {
    id: 'penghitung-kata',
    name: 'Penghitung Kata',
    slug: 'penghitung-kata',
    description: 'Hitung jumlah kata, huruf, kalimat, dan paragraf secara instan.',
    category: 'teks',
    icon: 'FileText',
  },
  {
    id: 'ubah-huruf',
    name: 'Ubah Huruf',
    slug: 'ubah-huruf',
    description: 'Ubah huruf KAPITAL, kecil, Judul, Kalimat, camelCase, dan snake_case.',
    category: 'teks',
    icon: 'Type',
  },
  {
    id: 'text-diff-checker',
    name: 'Text Diff Checker',
    slug: 'text-diff-checker',
    description: 'Bandingkan dua teks/kode untuk melihat perbedaannya (highlight merah/hijau).',
    category: 'teks',
    icon: 'GitCompare',
  },
  {
    id: 'markdown-live-preview',
    name: 'Markdown Live Preview',
    slug: 'markdown-live-preview',
    description: 'Editor teks untuk melihat hasil format Markdown secara real-time.',
    category: 'teks',
    icon: 'FileText',
  },
  {
    id: 'cari-ganti-teks',
    name: 'Cari & Ganti Teks',
    slug: 'cari-ganti-teks',
    description: 'Tempel teks Anda, cari frasa, lalu ganti otomatis.',
    category: 'teks',
    icon: 'SearchReplace',
  },
  {
    id: 'hapus-baris-duplikat',
    name: 'Hapus Baris Duplikat',
    slug: 'hapus-baris-duplikat',
    description: 'Bersihkan teks dari baris ganda hanya dengan satu klik.',
    category: 'teks',
    icon: 'Trash2',
  },
  {
    id: 'pembanding-teks',
    name: 'Pembanding Teks',
    slug: 'pembanding-teks',
    description: 'Alat pembanding teks untuk melihat perbedaan kata, kalimat, dan paragraf.',
    category: 'teks',
    icon: 'GitCompare',
  },
  {
    id: 'ascii-art',
    name: 'ASCII Art',
    slug: 'ascii-art',
    description: 'Ubah teks jadi ASCII Art dengan berbagai model huruf figlet menarik.',
    category: 'teks',
    icon: 'Hash',
  },
  
  // Image Tools
  {
    id: 'kompres-gambar',
    name: 'Kompres Gambar',
    slug: 'kompres-gambar',
    description: 'Kompres gambar JPG, PNG dan WebP online tanpa mengurangi kualitas.',
    category: 'gambar',
    icon: 'Image',
  },
  {
    id: 'crop-foto',
    name: 'Crop Foto',
    slug: 'crop-foto',
    description: 'Potong foto online langsung di browser, cepat dan mudah.',
    category: 'gambar',
    icon: 'Crop',
  },
  {
    id: 'hapus-latar-belakang',
    name: 'Hapus Latar Belakang',
    slug: 'hapus-latar-belakang',
    description: 'Hapus latar belakang foto secara otomatis sekali klik.',
    category: 'gambar',
    icon: 'Scissors',
  },
  {
    id: 'konversi-format-gambar',
    name: 'Konversi Format Gambar',
    slug: 'konversi-format-gambar',
    description: 'Ubah format gambar antara JPG, PNG, WebP, dan format lainnya.',
    category: 'gambar',
    icon: 'RefreshCw',
  },
  {
    id: 'signature-background-remover',
    name: 'Signature Background Remover',
    slug: 'signature-background-remover',
    description: 'Ubah foto tanda tangan kertas menjadi transparan (PNG) siap pakai.',
    category: 'gambar',
    icon: 'PenTool',
  },
  {
    id: 'screenshot-beautifier',
    name: 'Screenshot Beautifier',
    slug: 'screenshot-beautifier',
    description: 'Tambahkan frame browser/HP dan background estetik pada screenshot polos.',
    category: 'gambar',
    icon: 'Monitor',
  },
  {
    id: 'image-exif-remover',
    name: 'Image EXIF Remover',
    slug: 'image-exif-remover',
    description: 'Hapus data lokasi (GPS) dan detail kamera dari foto demi privasi.',
    category: 'gambar',
    icon: 'Shield',
  },
  {
    id: 'base64-image-encoder',
    name: 'Base64 Image Encoder',
    slug: 'base64-image-encoder',
    description: 'Ubah file gambar menjadi kode teks Base64 untuk embed HTML.',
    category: 'gambar',
    icon: 'Code',
  },
  
  // Audio Tools
  {
    id: 'kompres-audio',
    name: 'Kompres Audio',
    slug: 'kompres-audio',
    description: 'Kompres audio dengan preset cepat, estimasi hasil, dan pratinjau sebelum unduh.',
    category: 'audio',
    icon: 'Music',
  },
  {
    id: 'pemotong-audio',
    name: 'Pemotong Audio',
    slug: 'pemotong-audio',
    description: 'Potong atau pangkas audio dengan cepat tanpa kehilangan kualitas suara.',
    category: 'audio',
    icon: 'Scissors',
  },
  
  // Video Tools
  {
    id: 'kompres-video',
    name: 'Kompres Video',
    slug: 'kompres-video',
    description: 'Atur bitrate, resolusi, dan format video sesuai kebutuhan.',
    category: 'video',
    icon: 'Video',
  },
  {
    id: 'crop-video',
    name: 'Crop Video',
    slug: 'crop-video',
    description: 'Pangkas area video, ubah rasio aspek, dan unduh hasilnya tanpa watermark.',
    category: 'video',
    icon: 'Crop',
  },
  
  // Dev Tools
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    slug: 'json-formatter',
    description: 'Format & validasi JSON otomatis sekali klik.',
    category: 'dev',
    icon: 'Brackets',
  },
  {
    id: 'json-diff',
    name: 'JSON Diff',
    slug: 'json-diff',
    description: 'Bandingkan dua JSON lalu sorot perbedaan kunci, nilai, dan struktur.',
    category: 'dev',
    icon: 'GitCompare',
  },
  {
    id: 'minify-css',
    name: 'Minify CSS',
    slug: 'minify-css',
    description: 'Optimalkan ukuran stylesheet untuk performa lebih baik.',
    category: 'dev',
    icon: 'FileCode',
  },
  {
    id: 'minify-javascript',
    name: 'Minify Javascript',
    slug: 'minify-javascript',
    description: 'Percepat loading situs dengan minify JavaScript.',
    category: 'dev',
    icon: 'FileCode',
  },
  {
    id: 'unminify',
    name: 'Unminify',
    slug: 'unminify',
    description: 'Unminify dan pretty print JS, CSS, HTML, JSON Online.',
    category: 'dev',
    icon: 'FileText',
  },
  {
    id: 'javascript-obfuscator',
    name: 'Javascript Obfuscator',
    slug: 'javascript-obfuscator',
    description: 'Ubah kode menjadi sulit dibaca tanpa mengubah perilaku.',
    category: 'dev',
    icon: 'Lock',
  },
  {
    id: 'hapus-komentar',
    name: 'Hapus Komentar',
    slug: 'hapus-komentar',
    description: 'Hapus komentar dari kode HTML, CSS, dan JavaScript secara otomatis.',
    category: 'dev',
    icon: 'XCircle',
  },
  {
    id: 'json-to-csv',
    name: 'JSON to CSV / CSV to JSON',
    slug: 'json-to-csv',
    description: 'Konversi format data database secara instan di browser.',
    category: 'dev',
    icon: 'Table',
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    slug: 'sql-formatter',
    description: 'Merapikan kode SQL yang berantakan menjadi mudah dibaca.',
    category: 'dev',
    icon: 'Database',
  },
  {
    id: 'css-gradient-generator',
    name: 'CSS Gradient Generator',
    slug: 'css-gradient-generator',
    description: 'Visual editor untuk membuat kode warna gradasi CSS.',
    category: 'dev',
    icon: 'Palette',
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    slug: 'color-converter',
    description: 'Konversi kode warna antar format (HEX, RGB, HSL, CMYK).',
    category: 'dev',
    icon: 'Droplet',
  },
  
  // Network Tools
  {
    id: 'dns-lookup',
    name: 'DNS Lookup',
    slug: 'dns-lookup',
    description: 'Cek record DNS (A, AAAA, MX, TXT, CNAME, NS, SOA, PTR) & propagasi DNS.',
    category: 'jaringan',
    icon: 'Network',
  },
  {
    id: 'ip-lookup',
    name: 'IP Lookup',
    slug: 'ip-lookup',
    description: 'Masukkan IP atau domain, lihat geo, ASN/ISP, reverse DNS, CIDR.',
    category: 'jaringan',
    icon: 'Globe',
  },
  
  // Generator Tools
  {
    id: 'kode-qr',
    name: 'Kode QR',
    slug: 'kode-qr',
    description: 'Buat kode QR dengan warna custom langsung di browser.',
    category: 'generator',
    icon: 'QrCode',
  },
  {
    id: 'unix-timestamp-converter',
    name: 'Unix Timestamp Converter',
    slug: 'unix-timestamp-converter',
    description: 'Ubah angka waktu Unix menjadi tanggal yang bisa dibaca manusia (dan sebaliknya).',
    category: 'generator',
    icon: 'Clock',
  },
  {
    id: 'password',
    name: 'Password',
    slug: 'password',
    description: 'Buat kata sandi acak yang kuat dan unik dalam sekali klik.',
    category: 'generator',
    icon: 'Key',
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum',
    slug: 'lorem-ipsum',
    description: 'Hasilkan teks Lorem Ipsum acak untuk keperluan desain dan pengembangan web.',
    category: 'generator',
    icon: 'FileText',
  },
  {
    id: 'link-whatsapp',
    name: 'Link WhatsApp',
    slug: 'link-whatsapp',
    description: 'Buat link WhatsApp untuk memulai chat tanpa menyimpan nomor.',
    category: 'generator',
    icon: 'MessageCircle',
  },
  
  // Language Tools
  {
    id: 'youtube-transcript',
    name: 'Youtube Transcript Generator',
    slug: 'youtube-transcript',
    description: 'Tempel URL video, salin transkripnya dalam hitungan detik.',
    category: 'bahasa',
    icon: 'Youtube',
  },
  
  // Security Tools
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    slug: 'hash-generator',
    description: 'Generate hash MD5, SHA1, SHA256, SHA512, Django PBKDF2, dan lainnya.',
    category: 'dev',
    icon: 'Hash',
  },
  {
    id: 'minify-html',
    name: 'Minify HTML',
    slug: 'minify-html',
    description: 'Optimalkan ukuran file HTML untuk performa lebih baik.',
    category: 'dev',
    icon: 'FileCode',
  },
  {
    id: 'pembaca-readme',
    name: 'Pembaca README',
    slug: 'pembaca-readme',
    description: 'Baca README dari URL raw atau tempel manual, lalu salin isinya.',
    category: 'dev',
    icon: 'FileText',
  },
  {
    id: 'mock-data-generator',
    name: 'Mock Data Generator',
    slug: 'mock-data-generator',
    description: 'Buat ribuan data palsu (nama, alamat, email, HP) untuk testing DB.',
    category: 'generator',
    icon: 'Database',
  },
  {
    id: 'og-image-generator',
    name: 'OG Image Generator',
    slug: 'og-image-generator',
    description: 'Buat thumbnail Open Graph otomatis dari judul & deskripsi.',
    category: 'generator',
    icon: 'Image',
  },
  {
    id: 'pdf-invoice-generator',
    name: 'PDF Invoice Generator',
    slug: 'pdf-invoice-generator',
    description: 'Buat PDF invoice/kuitansi profesional siap cetak.',
    category: 'generator',
    icon: 'FileText',
  },
  {
    id: 'svg-shape-generator',
    name: 'SVG Blob & Wave Generator',
    slug: 'svg-shape-generator',
    description: 'Generate bentuk blob/wave organik untuk background modern.',
    category: 'generator',
    icon: 'BezierCurve',
  },
  {
    id: 'code-snippet-image',
    name: 'Code Snippet to Image',
    slug: 'code-snippet-image',
    description: 'Ubah kode jadi gambar estetik dengan syntax highlighting.',
    category: 'generator',
    icon: 'Code',
  },
  {
    id: 'e-certificate-generator',
    name: 'E-Certificate Generator',
    slug: 'e-certificate-generator',
    description: 'Bulk generate sertifikat dari template + daftar nama.',
    category: 'generator',
    icon: 'Award',
  },
  {
    id: 'github-profile-generator',
    name: 'GitHub Readme Profile Generator',
    slug: 'github-profile-generator',
    description: 'Form untuk membuat README profil GitHub siap pakai.',
    category: 'generator',
    icon: 'Github',
  },
  {
    id: 'css-glass-neumorphism',
    name: 'CSS Glass & Neumorphism',
    slug: 'css-glass-neumorphism',
    description: 'Generator efek glassmorphism dan neumorphism (slider).',
    category: 'generator',
    icon: 'Layers',
  },
  {
    id: 'wifi-card-generator',
    name: 'WiFi Card Generator',
    slug: 'wifi-card-generator',
    description: 'Buat kartu QR WiFi siap cetak dengan SSID & password.',
    category: 'generator',
    icon: 'Wifi',
  },
  {
    id: 'json-to-type',
    name: 'JSON to TS/Go',
    slug: 'json-to-type',
    description: 'Konversi JSON ke TypeScript Interface atau Go Struct.',
    category: 'dev',
    icon: 'Braces',
  },
  {
    id: 'random-palette-generator',
    name: 'Random Palette Generator',
    slug: 'random-palette-generator',
    description: 'Generate 5 warna harmonis, bisa lock sebagian.',
    category: 'generator',
    icon: 'Palette',
  },
  {
    id: 'pwa-manifest-icon',
    name: 'PWA Manifest & Icon',
    slug: 'pwa-manifest-icon',
    description: 'Generate manifest.json + resize icon standar PWA.',
    category: 'generator',
    icon: 'Smartphone',
  },
  {
    id: 'nginx-config-generator',
    name: 'Nginx Config Generator',
    slug: 'nginx-config-generator',
    description: 'GUI centang SSL/Gzip/Redirect, output nginx.conf.',
    category: 'dev',
    icon: 'Settings',
  },
  {
    id: 'barcode-generator',
    name: 'Barcode Generator',
    slug: 'barcode-generator',
    description: 'Buat barcode 1D (Code-128/EAN) ke SVG/Canvas.',
    category: 'generator',
    icon: 'Barcode',
  },
  {
    id: 'user-avatar-generator',
    name: 'User Avatar Generator',
    slug: 'user-avatar-generator',
    description: 'Avatar inisial nama dengan warna acak (SVG/Canvas).',
    category: 'generator',
    icon: 'User',
  },
]

export const categories = [
  { id: 'semua', name: 'Semua', icon: 'Grid' },
  { id: 'teks', name: 'Teks', icon: 'FileText' },
  { id: 'gambar', name: 'Gambar', icon: 'Image' },
  { id: 'audio', name: 'Audio', icon: 'Music' },
  { id: 'video', name: 'Video', icon: 'Video' },
  { id: 'dev', name: 'Dev', icon: 'Code' },
  { id: 'jaringan', name: 'Jaringan', icon: 'Network' },
  { id: 'generator', name: 'Generator', icon: 'Sparkles' },
  { id: 'bahasa', name: 'Bahasa', icon: 'Languages' },
] as const

export function getToolsByCategory(category: string): Tool[] {
  if (category === 'semua') return tools
  return tools.filter(tool => tool.category === category)
}

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find(tool => tool.slug === slug)
}

